package org.test.strategy;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.test.AnalysisResult;
import org.test.MatReportExtractor;
import org.test.parser.copilot.CopilotResponseParser;
import org.test.parser.copilot.LeakSuspectPromptCreator;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Objects;

/**
 * Strategy that sends the heap-analysis prompt to the
 * <a href="https://platform.openai.com/docs/api-reference/chat">OpenAI Chat
 * Completions API</a> and parses the JSON response into an
 * {@link AnalysisResult}.
 * <p>
 * The prompt is generated by {@link LeakSuspectPromptCreator} (same prompt
 * used for the manual Copilot flow) so the output schema is identical.
 * <p>
 * Environment:
 * <ul>
 *   <li>{@code OPENAI_API_KEY}  – required</li>
 *   <li>{@code OPENAI_MODEL}    – optional, defaults to {@code gpt-4o}</li>
 *   <li>{@code OPENAI_API_URL}  – optional, defaults to
 *       {@code https://api.openai.com/v1/chat/completions}</li>
 * </ul>
 */
public class OpenAiAnalysisStrategy implements HeapAnalysisStrategy {

    private static final Logger LOG = LoggerFactory.getLogger(OpenAiAnalysisStrategy.class);

    private static final String DEFAULT_API_URL = "https://api.openai.com/v1/chat/completions";
    private static final String DEFAULT_MODEL   = "gpt-4o";
    private static final int    MAX_TOKENS      = 4096;

    private final String       apiKey;
    private final String       model;
    private final String       apiUrl;
    private final HttpClient   http;
    private final ObjectMapper mapper;

    public OpenAiAnalysisStrategy(String apiKey) {
        this(apiKey,
             envOrDefault("OPENAI_MODEL", DEFAULT_MODEL),
             envOrDefault("OPENAI_API_URL", DEFAULT_API_URL));
    }

    public OpenAiAnalysisStrategy(String apiKey, String model, String apiUrl) {
        this.apiKey = Objects.requireNonNull(apiKey, "OPENAI_API_KEY must not be null");
        this.model  = model;
        this.apiUrl = apiUrl;
        this.http   = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(30))
                .build();
        this.mapper = new ObjectMapper();
    }

    @Override
    public AnalysisResult analyze(MatReportExtractor.MatReport report, int topN) throws Exception {
        LOG.info("[OpenAI] Building prompt (topN={})", topN);
        String prompt = new LeakSuspectPromptCreator()
                .withTopN(topN)
                .buildFromReport(report);
        LOG.info("[OpenAI] Prompt length: {} chars", prompt.length());

        LOG.info("[OpenAI] Calling {} model={}", apiUrl, model);
        String rawResponse = callOpenAi(prompt);
        LOG.info("[OpenAI] Response length: {} chars", rawResponse.length());

        LOG.info("[OpenAI] Parsing response into AnalysisResult");
        AnalysisResult result = CopilotResponseParser.parse(rawResponse);
        // Ensure provenance fields are populated
        if (result.heapDumpPath == null || result.heapDumpPath.isBlank()) {
            result.heapDumpPath = report.heapDumpPath;
        }
        LOG.info("[OpenAI] Analysis complete. Confidence={}", result.confidence);
        return result;
    }

    @Override
    public String strategyName() {
        return "OpenAI (" + model + ")";
    }

    // ── HTTP call ────────────────────────────────────────────────────────────

    private String callOpenAi(String userPrompt) throws Exception {
        ObjectNode body = mapper.createObjectNode();
        body.put("model", model);
        body.put("max_tokens", MAX_TOKENS);
        body.put("temperature", 0.2);

        ArrayNode messages = body.putArray("messages");

        ObjectNode systemMsg = messages.addObject();
        systemMsg.put("role", "system");
        systemMsg.put("content",
                "You are a senior Java performance engineer specialising in memory leak analysis. " +
                "Respond ONLY with a single valid JSON object. No markdown fences, no prose outside the JSON.");

        ObjectNode userMsg = messages.addObject();
        userMsg.put("role", "user");
        userMsg.put("content", userPrompt);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(apiUrl))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + apiKey)
                .POST(HttpRequest.BodyPublishers.ofString(
                        mapper.writeValueAsString(body), StandardCharsets.UTF_8))
                .timeout(Duration.ofSeconds(120))
                .build();

        HttpResponse<String> response =
                http.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new RuntimeException("OpenAI API error " + response.statusCode()
                    + ": " + response.body());
        }

        // Response: { "choices": [{ "message": { "content": "..." } }] }
        var root = mapper.readTree(response.body());
        var choices = root.path("choices");
        if (choices.isEmpty()) {
            throw new RuntimeException("Empty choices from OpenAI: " + response.body());
        }
        return choices.get(0).path("message").path("content").asText();
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private static String envOrDefault(String var, String def) {
        String v = System.getenv(var);
        return (v != null && !v.isBlank()) ? v : def;
    }
}

